version: '3.1'

services:

  drupal:
    image: drupal:7-apache
    container_name: trend_drupal
    ports:
      - ${EXTERNAL_LISTEN_PORT}:80
    restart: always
    volumes:
      - "drupal-data:/var/www"
    logging:
      driver: "json-file"
      options:
        max-size: 100m

  mysql:
    image: mysql:5.5
    container_name: trend_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASS}
    volumes:
      - "mysql-data:/var/lib/mysql"
    logging:
      driver: "json-file"
      options:
        max-size: 100m

  drush:
    container_name: trend_drush
    build: ./drush
    restart: always
    environment:
      DRUPAL_DIR: /var/www/html
      BACKUP_DIR: /backups
      BACKUP_PREFIX: trend-drupal
      MYSQL_PASS: ${MYSQL_PASS}
      CRON_SCHEDULE: ${DRUSH_BACKUP_CRON_SCHEDULE}
    volumes:
      - "drupal-data:/var/www"
      - "drush-backups:/backups"
      # we don't use this volume, but we deal with it to stop a new volume
      # being created everytime we bounce the stack
      - "drush-app:/app"
    logging:
      driver: "json-file"
      options:
        max-size: 100m

  awscli:
    container_name: trend_backup
    build: ./awscli
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - S3_BUCKET
      - CRON_SCHEDULE=${S3_SYNC_CRON_SCHEDULE}
      - BACKUP_DIR=/backups
    volumes:
      - "drush-backups:/backups:ro"
    logging:
      driver: "json-file"
      options:
        max-size: 100m

volumes:
  drupal-data:
  drush-backups:
  drush-app:
  mysql-data:
