version: '3.1'

services:

  drupal:
    image: drupal:7-apache
    ports:
      - 8080:80
    restart: always

  mysql:
    image: mysql:5.5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
